name: "Setup Java and Maven"
description: "Setup Java and Maven"

inputs:
  mavenVersion:
    description: "Maven version to be installed"
    required: false
    default: "3.9.9"
  javaVersion:
    description: "Java version to be installed"
    required: false
    default: "21"
  javaDistro:
    description: "Java distribution to be installed"
    required: false
    default: "temurin"

runs:
  using: "composite"
  steps:
    - name: Set up Maven
      uses: stCarolas/setup-maven@12eb41b233df95d49b0c11fc1b5bc8312e5d4ce0 # v5.1
      with:
        maven-version: ${{ inputs.mavenVersion }}

    - uses: actions/setup-java@ad2b38190b15e4d6bdf0c97fb4fca8412226d287 # v5.3.0
      with:
        distribution: ${{ inputs.javaDistro }}
        java-version: ${{ inputs.javaVersion }}
