name: "Install Docker"
description: "Install Docker"

runs:
  using: "composite"
  steps:
    - name: Check docker version
      shell: bash
      run: "docker --version"

    - name: Set up QEMU
      uses: docker/setup-qemu-action@99012661954931238ded8c8b007157a8430204e1 # v4.4.0
      with:
        platforms: all

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@f87e5991a6d7451dcb8d9637bfbc97413f497069 # v4.4.1
      with:
        platforms: linux/amd64,linux/arm64,linux/ppc64le,linux/s390x
        driver: docker
        use: true

    - name: Check buildx
      shell: bash
      run: docker buildx inspect --bootstrap
